item {
  name: "Bend"
  id: 1
}
item {
  name: "Look at screen"
  id: 2
}
item {
  name: "Sit"
  id: 3
}
item {
  name: "Stand"
  id: 4
}
item {
  name: "Talk"
  id: 5
}
item {
  name: "Walk"
  id: 6
}