item {
  name: "Look At Screen"
  id: 1
}

item {
  name: "Sit"
  id: 2
}

item {
  name: "Sleep"
  id: 3
}

item {
  name: "Stand"
  id: 4
}

item {
  name: "Talk"
  id: 5
}

item {
  name: "Use Phone"
  id: 6
}