TRAIN:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 16
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: path to pretrain model
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [360, 640]
  TRAIN_CROP_SIZE: 360
  TEST_CROP_SIZE: 360
  INPUT_CHANNEL_NUM: [3, 3]
DETECTION:
  ENABLE: True
  ALIGNED: False
AVA:
  BGR: False
  DETECTION_SCORE_THRESH: 0.8
  # TRAIN_GT_BOX_LISTS: ["ava_train.csv"]
  TRAIN_PREDICT_BOX_LISTS: ["/content/ava_dataset/annotations/person_box_67091280_iou90/ava_detection_train_boxes_and_labels_include_negative_v2.2.csv"]
  TEST_PREDICT_BOX_LISTS: ["/content/ava_dataset/annotations/person_box_67091280_iou90/ava_detection_val_boxes_and_labels.csv"]
  # EXCLUSION_FILE: "ava_val_excluded_timestamps_v2.1.csv"
  # LABEL_MAP_FILE: ava_action_list_v2.1_for_activitynet_2018.pbtxt
  # GROUNDTRUTH_FILE: ava_val.csv
  FRAME_LIST_DIR: /content/ava_dataset/frame_lists
  ANNOTATION_DIR: /content/ava_dataset/annotations
  FRAME_DIR: /content/ava_dataset/frames
  FULL_TEST_ON_VAL: True
  LABEL_MAP_FILE: ava_action_list.pbtxt
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 6
  ARCH: slowfast
  MODEL_NAME: PTVSlowFast
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid
TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 1
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: output
TENSORBOARD:
  ENABLE: True

# DEMO:
#   ENABLE: True
#   LABEL_FILE_PATH: ava_action_list_v2.2_for_activitynet_2019.pbtxt
#   INPUT_VIDEO: /content/drive/MyDrive/test.avi
#   # OUTPUT_FILE: